name: Scrape FlowAgility diario

on:
  schedule:
    - cron: '5 2 * * *'
  workflow_dispatch:

jobs:
  run_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      TZ: Europe/Madrid
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Chrome
        id: setup_chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: stable
          install-dependencies: true
          install-chromedriver: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install selenium webdriver-manager beautifulsoup4 python-dotenv
          fi

      - name: Run scraper
        env:
          FLOW_USER_EMAIL: ${{ secrets.FLOW_USER_EMAIL }}
          FLOW_USER_PASSWORD: ${{ secrets.FLOW_USER_PASSWORD }}
          HEADLESS: "true"
          INCOGNITO: "true"
          OUT_DIR: "./output"
          CHROME_BINARY: ${{ steps.setup_chrome.outputs.chrome-path }}
          CHROMEDRIVER_PATH: ${{ steps.setup_chrome.outputs.chromedriver-path }}
        run: |
          set -euo pipefail
          python ./Calendario.py

      - name: Find output
        id: find
        run: |
          set -euo pipefail
          CSV_PATH="$(find . -type f -name 'eventos_prox.csv' -print -quit || true)"
          JSON_PATH="$(find . -type f -name 'events.json' -print -quit || true)"
          if [ -n "$CSV_PATH" ]; then
            ART="$CSV_PATH"; NAME="eventos_prox.csv"
          elif [ -n "$JSON_PATH" ]; then
            ART="$JSON_PATH"; NAME="events.json"
          else
            echo "::error::No output file found (eventos_prox.csv or events.json)"; exit 1
          fi
          echo "artifact_path=$ART"  >> "$GITHUB_OUTPUT"
          echo "artifact_name=$NAME" >> "$GITHUB_OUTPUT"
          sha256sum "$ART" | awk '{print $1}' > local.sha256
          echo "local_hash=$(cut -d' ' -f1 local.sha256)" >> "$GITHUB_OUTPUT"
          echo "local_size=$(stat -c%s "$ART")" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.find.outputs.artifact_name }}
          path: ${{ steps.find.outputs.artifact_path }}
          if-no-files-found: error
          retention-days: 7

      - name: Check FTP secrets
        id: hasftp
        env:
          FTP_SERVER:     ${{ secrets.FTP_SERVER }}
          FTP_USERNAME:   ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD:   ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
        run: |
          set -euo pipefail
          if [ -n "${FTP_SERVER:-}" ] && [ -n "${FTP_USERNAME:-}" ] && [ -n "${FTP_PASSWORD:-}" ] && [ -n "${FTP_REMOTE_DIR:-}" ]; then
            echo "ok=true" >> "$GITHUB_OUTPUT"
          else
            echo "ok=false" >> "$GITHUB_OUTPUT"
          fi

      - name: List remote (pre)
        if: ${{ steps.find.outputs.artifact_name == 'eventos_prox.csv' && steps.hasftp.outputs.ok == 'true' }}
        env:
          FTP_SERVER:     ${{ secrets.FTP_SERVER }}
          FTP_USERNAME:   ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD:   ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
        run: |
          set -euo pipefail
          BASE="ftp://${FTP_SERVER}${FTP_REMOTE_DIR}/Competiciones/ListadoEventos"
          echo "Listing: ${BASE}/"
          curl --fail --ssl-reqd --user "${FTP_USERNAME}:${FTP_PASSWORD}" "${BASE}/" -l || true

      - name: Upload CSV via FTPS
        if: ${{ steps.find.outputs.artifact_name == 'eventos_prox.csv' && steps.hasftp.outputs.ok == 'true' }}
        env:
          FTP_SERVER:     ${{ secrets.FTP_SERVER }}
          FTP_USERNAME:   ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD:   ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
        run: |
          set -euo pipefail
          FULL_DIR="${FTP_REMOTE_DIR}/Competiciones/ListadoEventos"
          BASE="ftp://${FTP_SERVER}${FULL_DIR}"
          FILE="eventos_prox.csv"
          TMP="${BASE}/${FILE}.part"
          SRC="${{ steps.find.outputs.artifact_path }}"

          echo "Uploading temp: $TMP"
          curl --fail --ssl-reqd --ftp-create-dirs --disable-epsv --ftp-skip-pasv-ip \
               --quote "TYPE I" --quote "PBSZ 0" --quote "PROT P" \
               --user "${FTP_USERNAME}:${FTP_PASSWORD}" \
               --upload-file "$SRC" "$TMP"

          echo "Renaming to final"
          curl --fail --ssl-reqd \
               --user "${FTP_USERNAME}:${FTP_PASSWORD}" \
               --quote "RNFR ${FULL_DIR}/${FILE}.part" \
               --quote "RNTO ${FULL_DIR}/${FILE}" \
               "ftp://${FTP_SERVER}/"

      - name: Verify remote
        if: ${{ steps.find.outputs.artifact_name == 'eventos_prox.csv' && steps.hasftp.outputs.ok == 'true' }}
        env:
          FTP_SERVER:     ${{ secrets.FTP_SERVER }}
          FTP_USERNAME:   ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD:   ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
        run: |
          set -euo pipefail
          BASE="ftp://${FTP_SERVER}${FTP_REMOTE_DIR}/Competiciones/ListadoEventos"
          FILE="eventos_prox.csv"

          echo "Listing after upload: ${BASE}/"
          curl --fail --ssl-reqd --user "${FTP_USERNAME}:${FTP_PASSWORD}" "${BASE}/" -l

          echo "Downloading for verification"
          curl --fail --ssl-reqd --disable-epsv --ftp-skip-pasv-ip \
               --user "${FTP_USERNAME}:${FTP_PASSWORD}" \
               --output remote.csv "${BASE}/${FILE}"

          sha256sum remote.csv | awk '{print $1}' > remote.sha256
          echo "Local hash : ${{ steps.find.outputs.local_hash }}"
          echo "Remote hash: $(cut -d' ' -f1 remote.sha256)"
          diff -q local.sha256 remote.sha256

          REMOTE_SIZE=$(stat -c%s remote.csv)
          echo "Remote size: $REMOTE_SIZE bytes"
          test "$REMOTE_SIZE" -eq "${{ steps.find.outputs.local_size }}"
          echo "OK: hash and size match"
