- name: Comprobar que los secrets existen
  run: |
    for s in FTP_SERVER FTP_USERNAME FTP_PASSWORD FTP_REMOTE_DIR; do
      if [ -z "${!s}" ]; then echo "❌ Falta $s"; exit 1; else echo "✅ $s OK"; fi
    done
  env:
    FTP_SERVER: ${{ secrets.FTP_SERVER }}
    FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
    FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
    FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
